apiVersion: v2
name: Texol_213MM1-B1_v2_10
manufacturer: Texol
description: 3 Axis BLE Vibration Sensor Profile
model: 213MM1-B1_v2_10
labels:
- MQTT_BLE
deviceResources:
- name: RPM
  description: ''
  properties:
    valueType: Uint16
    readWrite: R
  attributes:
    qos: '0'
    msgFormat: json
    jsonPath: Feature.RPM
    subTopic: /TEXOL/213MM1-B1/${topicReplacement}
  isHidden: false
- name: X_Overall
  description: ''
  properties:
    valueType: Float32
    readWrite: R
  attributes:
    qos: '0'
    msgFormat: json
    jsonPath: Feature.XOA
    subTopic: /TEXOL/213MM1-B1/${topicReplacement}
  isHidden: false
- name: Y_Overall
  description: ''
  properties:
    valueType: Float32
    readWrite: R
  attributes:
    qos: '0'
    msgFormat: json
    jsonPath: Feature.YOA
    subTopic: /TEXOL/213MM1-B1/${topicReplacement}
  isHidden: false
- name: Z_Overall
  description: ''
  properties:
    valueType: Float32
    readWrite: R
  attributes:
    qos: '0'
    msgFormat: json
    jsonPath: Feature.ZOA
    subTopic: /TEXOL/213MM1-B1/${topicReplacement}
  isHidden: false
- name: X_Power_in_Band_01
  description: ''
  properties:
    valueType: Float32
    readWrite: R
  attributes:
    qos: '0'
    msgFormat: json
    jsonPath: Feature.XPIB01
    subTopic: /TEXOL/213MM1-B1/${topicReplacement}
  isHidden: false
- name: X_Power_in_Band_02
  description: ''
  properties:
    valueType: Float32
    readWrite: R
  attributes:
    qos: '0'
    msgFormat: json
    jsonPath: Feature.XPIB02
    subTopic: /TEXOL/213MM1-B1/${topicReplacement}
  isHidden: false
- name: X_Power_in_Band_03
  description: ''
  properties:
    valueType: Float32
    readWrite: R
  attributes:
    qos: '0'
    msgFormat: json
    jsonPath: Feature.XPIB03
    subTopic: /TEXOL/213MM1-B1/${topicReplacement}
  isHidden: false
- name: Y_Power_in_Band_01
  description: ''
  properties:
    valueType: Float32
    readWrite: R
  attributes:
    qos: '0'
    msgFormat: json
    jsonPath: Feature.YPIB01
    subTopic: /TEXOL/213MM1-B1/${topicReplacement}
  isHidden: false
- name: Y_Power_in_Band_02
  description: ''
  properties:
    valueType: Float32
    readWrite: R
  attributes:
    qos: '0'
    msgFormat: json
    jsonPath: Feature.YPIB02
    subTopic: /TEXOL/213MM1-B1/${topicReplacement}
  isHidden: false
- name: Y_Power_in_Band_03
  description: ''
  properties:
    valueType: Float32
    readWrite: R
  attributes:
    qos: '0'
    msgFormat: json
    jsonPath: Feature.YPIB03
    subTopic: /TEXOL/213MM1-B1/${topicReplacement}
  isHidden: false
- name: Z_Power_in_Band_01
  description: ''
  properties:
    valueType: Float32
    readWrite: R
  attributes:
    qos: '0'
    msgFormat: json
    jsonPath: Feature.ZPIB01
    subTopic: /TEXOL/213MM1-B1/${topicReplacement}
  isHidden: false
- name: Z_Power_in_Band_02
  description: ''
  properties:
    valueType: Float32
    readWrite: R
  attributes:
    qos: '0'
    msgFormat: json
    jsonPath: Feature.ZPIB02
    subTopic: /TEXOL/213MM1-B1/${topicReplacement}
  isHidden: false
- name: Z_Power_in_Band_03
  description: ''
  properties:
    valueType: Float32
    readWrite: R
  attributes:
    qos: '0'
    msgFormat: json
    jsonPath: Feature.ZPIB03
    subTopic: /TEXOL/213MM1-B1/${topicReplacement}
  isHidden: false
- name: Looseness
  description: ''
  properties:
    valueType: Float32
    readWrite: R
  attributes:
    qos: '0'
    msgFormat: json
    jsonPath: Feature.Looseness
    subTopic: /TEXOL/213MM1-B1/${topicReplacement}
  isHidden: false
- name: Misalignment
  description: ''
  properties:
    valueType: Float32
    readWrite: R
  attributes:
    qos: '0'
    msgFormat: json
    jsonPath: Feature.Misalignment
    subTopic: /TEXOL/213MM1-B1/${topicReplacement}
  isHidden: false
- name: Unbalance
  description: ''
  properties:
    valueType: Float32
    readWrite: R
  attributes:
    qos: '0'
    msgFormat: json
    jsonPath: Feature.Unbalance
    subTopic: /TEXOL/213MM1-B1/${topicReplacement}
  isHidden: false
- name: Sensor_Heartbeat
  description: ''
  properties:
    valueType: String
    readWrite: R
  attributes:
    qos: '0'
    msgFormat: json
    jsonPath: Feature
    subTopic: /TEXOL/213MM1-B1/${topicReplacement}/HEARTBEAT
  isHidden: false
- name: Bridge_UUID
  description: ''
  properties:
    valueType: String
    readWrite: R
  attributes:
    qos: '0'
    msgFormat: json
    jsonPath: BridgeUUID
    subTopic: /TEXOL/213MM1-B1/${topicReplacement}
  isHidden: false
- name: Channel
  description: ''
  properties:
    valueType: String
    readWrite: R
  attributes:
    qos: '0'
    msgFormat: json
    jsonPath: Channel
    subTopic: /TEXOL/213MM1-B1/${topicReplacement}
  isHidden: false
- name: Pipe
  description: ''
  properties:
    valueType: String
    readWrite: R
  attributes:
    qos: '0'
    msgFormat: json
    jsonPath: Pipe
    subTopic: /TEXOL/213MM1-B1/${topicReplacement}
  isHidden: false
- name: BLE_UUID
  description: ''
  properties:
    valueType: String
    readWrite: R
  attributes:
    qos: '0'
    msgFormat: json
    jsonPath: BLEUUID
    subTopic: /TEXOL/213MM1-B1/${topicReplacement}
  isHidden: false
- name: Sensor_ID
  description: ''
  properties:
    valueType: String
    readWrite: R
  attributes:
    qos: '0'
    msgFormat: json
    jsonPath: SensorID
    subTopic: /TEXOL/213MM1-B1/${topicReplacement}
  isHidden: false
- name: Module_Name
  description: ''
  properties:
    valueType: String
    readWrite: R
  attributes:
    qos: '0'
    msgFormat: json
    jsonPath: ModuleName
    subTopic: /TEXOL/213MM1-B1/${topicReplacement}
  isHidden: false
- name: BLE_FW_Version
  description: ''
  properties:
    valueType: String
    readWrite: R
  attributes:
    qos: '0'
    msgFormat: json
    jsonPath: BLEFWVersion
    subTopic: /TEXOL/213MM1-B1/${topicReplacement}
  isHidden: false
- name: RSSI
  description: ''
  properties:
    valueType: String
    readWrite: R
  attributes:
    qos: '0'
    msgFormat: json
    jsonPath: RSSI
    subTopic: /TEXOL/213MM1-B1/${topicReplacement}
  isHidden: false
deviceCommands: []
