{
 "title": "211HM1-B1-Template",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "information",
   "type": "table",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "query": "from(bucket: \"bucket\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"readings\")\r\n  |> filter(fn: (r) => r[\"deviceName\"] == \"Sensor01\")\r\n\r\n  |> filter(fn: (r) => r[\"_field\"] == \"Bridge_UUID\" or r[\"_field\"] == \"Channel\" or r[\"_field\"] == \"Pipe\" or r[\"_field\"] == \"BLE_UUID\" or r[\"_field\"] == \"Sensor_ID\")\r\n  |> drop(columns: [\"_start\", \"_stop\",\"SensorID\",\"resourceName\",\"_measurement\"])  \r\n  |> pivot(rowKey:[\"deviceName\"], columnKey: [\"_field\"], valueColumn: \"_value\")  \r\n  |> yield(name: \"custom-name\")    \r\n  \r\n\r\n  \r\n    "
    }
   ]
  },
  {
   "title": "Panel Title",
   "type": "text",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 3 },
   "options": {
    "content": "<div class=\"bg\">\n    <img src=\"/public/img/texol/TEXOL Aurora 211HM1-B1.jpg\"\n    width=100% >\n  </div>\n"
   }
  },
  {
   "title": "Z_Overall (mm/s,rms)",
   "type": "stat",
   "gridPos": { "h": 8, "w": 10, "x": 4, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"bucket\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"readings\")\n  |> filter(fn: (r) => r[\"deviceName\"] == \"Sensor01\")\n  \n  |> filter(fn: (r) => r[\"_field\"] == \"Z_Overall\")\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\n  |> yield(name: \"last\")"
    }
   ]
  },
  {
   "title": "RPM",
   "type": "stat",
   "gridPos": { "h": 8, "w": 10, "x": 14, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"bucket\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"readings\")\n  |> filter(fn: (r) => r[\"deviceName\"] == \"Sensor01\")\n  \n  |> filter(fn: (r) => r[\"_field\"] == \"RPM\")\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\n  |> yield(name: \"last\")"
    }
   ]
  },
  {
   "title": "Bearing Defect",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 11 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"bucket\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"readings\")\n  |> filter(fn: (r) => r[\"deviceName\"] == \"Sensor01\")\n  \n  |> filter(fn: (r) => r[\"_field\"] ==  \"Bearing\")\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\n  |> yield(name: \"last\")"
    }
   ]
  },
  {
   "title": "Unbalance Energy [(mm/s,rms)^2]",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 11 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"bucket\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"readings\")\n |> filter(fn: (r) => r[\"deviceName\"] == \"Sensor01\")\n \n  |> filter(fn: (r) => r[\"_field\"] == \"Unbalance\")\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\n  |> yield(name: \"last\")"
    }
   ]
  },
  {
   "title": "Misalignment  Energy [(mm/s,rms)^2]",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 11 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"bucket\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"readings\")\n  |> filter(fn: (r) => r[\"deviceName\"] == \"Sensor01\")\n  \n  |> filter(fn: (r) => r[\"_field\"] == \"Misalignment\")\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\n  |> yield(name: \"last\")"
    }
   ]
  },
  {
   "title": "Looseness Energy [(mm/s,rms)^2]",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 11 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"bucket\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"readings\")\n  |> filter(fn: (r) => r[\"deviceName\"] == \"Sensor01\")\n  \n  |> filter(fn: (r) => r[\"_field\"] ==  \"Looseness\")\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\n  |> yield(name: \"last\")"
    }
   ]
  },
  {
   "title": "Gear_mesh Energy [(mm/s,rms)^2]",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 11 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"bucket\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"readings\")\n  |> filter(fn: (r) => r[\"deviceName\"] == \"Sensor01\")\n  \n  |> filter(fn: (r) => r[\"_field\"] == \"Gear_mesh\")\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\n  |> yield(name: \"last\")"
    }
   ]
  },
  {
   "title": "Van_Pass Energy [(mm/s,rms)^2]",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 11 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"bucket\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"readings\")\n  |> filter(fn: (r) => r[\"deviceName\"] == \"Sensor01\")\n  \n  |> filter(fn: (r) => r[\"_field\"] ==  \"Van_Pass\")\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\n  |> yield(name: \"last\")"
    }
   ]
  },
  {
   "title": "Unbalance Energy Percentage",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"bucket\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"readings\")\n  |> filter(fn: (r) => r[\"deviceName\"] == \"Sensor01\")\n  \n  |> filter(fn: (r) => r[\"_field\"] ==  \"Unbalance_percentage\")\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\n  |> yield(name: \"last\")"
    }
   ]
  },
  {
   "title": "Misalignment Energy Percentage",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"bucket\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"readings\")\n  |> filter(fn: (r) => r[\"deviceName\"] == \"Sensor01\")\n  \n  |> filter(fn: (r) => r[\"_field\"] ==  \"Misalignment_percentage\")\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\n  |> yield(name: \"last\")"
    }
   ]
  },
  {
   "title": "Looseness Energy Percentage",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"bucket\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"readings\")\n  |> filter(fn: (r) => r[\"deviceName\"] == \"Sensor01\")\n  \n  |> filter(fn: (r) => r[\"_field\"] ==  \"Looseness_percentage\")\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\n  |> yield(name: \"last\")"
    }
   ]
  },
  {
   "title": "Gear_mesh Energy Percentage",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"bucket\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"readings\")\n  |> filter(fn: (r) => r[\"deviceName\"] == \"Sensor01\")\n  \n  |> filter(fn: (r) => r[\"_field\"] ==  \"Gear_mesh_percentage\")\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\n  |> yield(name: \"last\")"
    }
   ]
  },
  {
   "title": "Van_Pass Energy Percentage",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"bucket\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"readings\")\n  |> filter(fn: (r) => r[\"deviceName\"] == \"Sensor01\")\n  \n  |> filter(fn: (r) => r[\"_field\"] == \"Van_Pass_percentage\")\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\n  |> yield(name: \"last\")"
    }
   ]
  },
  { "type": "text", "gridPos": { "h": 2, "w": 24, "x": 0, "y": 19 }, "options": { "content": "Trend-Hourly" } },
  {
   "title": "Overall (mm/s,rms)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 21 },
   "targets": [
    {
     "query": "from(bucket: \"Hourly_Bucket\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"readings\")\n  |> filter(fn: (r) => r[\"deviceName\"] == \"Sensor01\")\n  \n  |> filter(fn: (r) => r[\"_field\"] ==  \"X_Overall\" or r[\"resourceName\"] == \"Y_Overall\" or r[\"resourceName\"] == \"Z_Overall\")\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Failure mode [(mm/s,rms)^2]",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 29 },
   "targets": [
    {
     "query": "from(bucket: \"Hourly_Bucket\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"readings\")\n  |> filter(fn: (r) => r[\"deviceName\"] == \"Sensor01\")\n  \n  |> filter(fn: (r) => r[\"_field\"] == \"Bearing\" or r[\"_field\"] == \"Unbalance\" or r[\"_field\"] == \"Misalignment\" or r[\"_field\"] == \"Looseness\" or r[\"_field\"] == \"Gear_mesh\" or r[\"_field\"] == \"Van_Pass\")\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Failure mode_percentage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "query": "from(bucket: \"Hourly_Bucket\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"readings\")\n  |> filter(fn: (r) => r[\"deviceName\"] == \"Sensor01\")\n  \n  |> filter(fn: (r) => r[\"_field\"] == \"Bearing_percentage\" or r[\"_field\"] == \"Gear_mesh_percentage\" or r[\"_field\"] == \"Looseness_percentage\" or r[\"_field\"] == \"Misalignment_percentage\" or r[\"_field\"] == \"Unbalance_percentage\" or r[\"_field\"] == \"Van_Pass_percentage\")\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> yield(name: \"mean\")"
    }
   ]
  },
  { "type": "text", "gridPos": { "h": 2, "w": 24, "x": 0, "y": 45 }, "options": { "content": "Trend-Daily" } },
  {
   "title": "Z_Overall",
   "type": "stat",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 47 },
   "fieldConfig": { "defaults": { "unit": "d" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"Daily_Bucket\")\n  |> range(start: 2023-01-01T00:00:00Z)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"readings\")\n  |> filter(fn: (r) => r[\"deviceName\"] == \"Sensor01\")\n  \n  |> filter(fn: (r) => r[\"_field\"] == \"Z_Overall\")\n  |> difference(nonNegative: false, columns: [\"_value\"])\n  |> stateCount(fn: (r) => r._value >0, column: \"stateCount\") \n  |> map(fn: (r) => ({ r with _value: if r.stateCount >0 then r.stateCount else 0 })) \n  |> drop(columns: [\"stateCount\"]) \n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\n  |> yield(name: \"last\")"
    }
   ]
  },
  {
   "title": "Overall (mm/s,rms)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 51 },
   "targets": [
    {
     "query": "from(bucket: \"Daily_Bucket\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"readings\")\n  |> filter(fn: (r) => r[\"deviceName\"] == \"Sensor01\")\n  \n  |> filter(fn: (r) => r[\"_field\"] ==  \"X_Overall\" or r[\"resourceName\"] == \"Y_Overall\" or r[\"resourceName\"] == \"Z_Overall\")\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Bearing Defect",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 59 },
   "fieldConfig": { "defaults": { "unit": "d" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"Daily_Bucket\")\n  |> range(start: 2023-01-01T00:00:00Z)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"readings\")\n  |> filter(fn: (r) => r[\"deviceName\"] == \"Sensor01\")\n  \n  |> filter(fn: (r) => r[\"_field\"] == \"Bearing\")\n  |> difference(nonNegative: false, columns: [\"_value\"])\n  |> stateCount(fn: (r) => r._value >0, column: \"stateCount\") \n  |> map(fn: (r) => ({ r with _value: if r.stateCount >0 then r.stateCount else 0 })) \n  |> drop(columns: [\"stateCount\"]) \n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\n  |> yield(name: \"last\")"
    }
   ]
  },
  {
   "title": "Unbalance Energy",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 59 },
   "fieldConfig": { "defaults": { "unit": "d" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"Daily_Bucket\")\n  |> range(start: 2023-01-01T00:00:00Z)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"readings\")\n  |> filter(fn: (r) => r[\"deviceName\"] == \"Sensor01\")\n  \n  |> filter(fn: (r) => r[\"_field\"] == \"Unbalance\")\n  |> difference(nonNegative: false, columns: [\"_value\"])\n  |> stateCount(fn: (r) => r._value >0, column: \"stateCount\") \n  |> map(fn: (r) => ({ r with _value: if r.stateCount >0 then r.stateCount else 0 })) \n  |> drop(columns: [\"stateCount\"]) \n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\n  |> yield(name: \"last\")"
    }
   ]
  },
  {
   "title": "Misalignment Energy",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 59 },
   "fieldConfig": { "defaults": { "unit": "d" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"Daily_Bucket\")\n  |> range(start: 2023-01-01T00:00:00Z)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"readings\")\n  |> filter(fn: (r) => r[\"deviceName\"] == \"Sensor01\")\n  \n  |> filter(fn: (r) => r[\"_field\"] == \"Misalignment\")\n  |> difference(nonNegative: false, columns: [\"_value\"])\n  |> stateCount(fn: (r) => r._value >0, column: \"stateCount\") \n  |> map(fn: (r) => ({ r with _value: if r.stateCount >0 then r.stateCount else 0 })) \n  |> drop(columns: [\"stateCount\"]) \n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\n  |> yield(name: \"last\")"
    }
   ]
  },
  {
   "title": "Losseness Energy",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 59 },
   "fieldConfig": { "defaults": { "unit": "d" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"Daily_Bucket\")\n  |> range(start: 2023-01-01T00:00:00Z)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"readings\")\n  |> filter(fn: (r) => r[\"deviceName\"] == \"Sensor01\")\n  \n  |> filter(fn: (r) => r[\"_field\"] == \"Looseness\")\n  |> difference(nonNegative: false, columns: [\"_value\"])\n  |> stateCount(fn: (r) => r._value >0, column: \"stateCount\") \n  |> map(fn: (r) => ({ r with _value: if r.stateCount >0 then r.stateCount else 0 })) \n  |> drop(columns: [\"stateCount\"]) \n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\n  |> yield(name: \"last\")"
    }
   ]
  },
  {
   "title": "Gear_mesh Energy",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 59 },
   "fieldConfig": { "defaults": { "unit": "d" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"Daily_Bucket\")\n  |> range(start: 2023-01-01T00:00:00Z)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"readings\")\n  |> filter(fn: (r) => r[\"deviceName\"] == \"Sensor01\")\n  \n  |> filter(fn: (r) => r[\"_field\"] == \"Gear_mesh\")\n  |> difference(nonNegative: false, columns: [\"_value\"])\n  |> stateCount(fn: (r) => r._value >0, column: \"stateCount\") \n  |> map(fn: (r) => ({ r with _value: if r.stateCount >0 then r.stateCount else 0 })) \n  |> drop(columns: [\"stateCount\"]) \n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\n  |> yield(name: \"last\")"
    }
   ]
  },
  {
   "title": "Van_Pass Energy",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 59 },
   "fieldConfig": { "defaults": { "unit": "d" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"Daily_Bucket\")\n  |> range(start: 2023-01-01T00:00:00Z)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"readings\")\n  |> filter(fn: (r) => r[\"deviceName\"] == \"Sensor01\")\n  \n  |> filter(fn: (r) => r[\"_field\"] == \"Van_Pass\")\n  |> difference(nonNegative: false, columns: [\"_value\"])\n  |> stateCount(fn: (r) => r._value >0, column: \"stateCount\") \n  |> map(fn: (r) => ({ r with _value: if r.stateCount >0 then r.stateCount else 0 })) \n  |> drop(columns: [\"stateCount\"]) \n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\n  |> yield(name: \"last\")"
    }
   ]
  },
  {
   "title": "Failure mode [(mm/s,rms)^2]",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 63 },
   "targets": [
    {
     "query": "from(bucket: \"Daily_Bucket\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"readings\")\n  |> filter(fn: (r) => r[\"deviceName\"] == \"Sensor01\")\n  \n  |> filter(fn: (r) => r[\"_field\"] == \"Bearing\" or r[\"_field\"] == \"Unbalance\" or r[\"_field\"] == \"Misalignment\" or r[\"_field\"] == \"Looseness\" or r[\"_field\"] == \"Gear_mesh\" or r[\"_field\"] == \"Van_Pass\")\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Failure mode_percentage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 71 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "query": "from(bucket: \"Daily_Bucket\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"readings\")\n  |> filter(fn: (r) => r[\"deviceName\"] == \"Sensor01\")\n  \n  |> filter(fn: (r) => r[\"_field\"] == \"Bearing_percentage\" or r[\"_field\"] == \"Gear_mesh_percentage\" or r[\"_field\"] == \"Looseness_percentage\" or r[\"_field\"] == \"Misalignment_percentage\" or r[\"_field\"] == \"Unbalance_percentage\" or r[\"_field\"] == \"Van_Pass_percentage\")\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> yield(name: \"mean\")"
    }
   ]
  }
 ]
}