{
 "title": "213MM1-B1-Temp",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Panel Title",
   "type": "text",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 0 },
   "options": {
    "content": "<div class=\"bg\">\n    <img src=\"/public/img/texol/TEXOL Aurora 213MM1-B1.jpg\"\n    width=100% >\n  </div>\n"
   }
  },
  {
   "title": "X_Overall (mm/s,rms)",
   "type": "stat",
   "gridPos": { "h": 8, "w": 5, "x": 4, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"bucket\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"readings\")\n  |> filter(fn: (r) => r[\"deviceName\"] == \"Sensor06\")\n  |> filter(fn: (r) => r[\"_field\"] == \"X_Overall\")\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\n  |> yield(name: \"last\")"
    }
   ]
  },
  {
   "title": "Y_Overall (mm/s,rms)",
   "type": "stat",
   "gridPos": { "h": 8, "w": 5, "x": 9, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"bucket\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"readings\")\n  |> filter(fn: (r) => r[\"deviceName\"] == \"Sensor06\")\n  |> filter(fn: (r) => r[\"_field\"] == \"Y_Overall\")\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\n  |> yield(name: \"last\")"
    }
   ]
  },
  {
   "title": "Z_Overall (mm/s,rms)",
   "type": "stat",
   "gridPos": { "h": 8, "w": 5, "x": 14, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"bucket\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"readings\")\n  |> filter(fn: (r) => r[\"deviceName\"] == \"Sensor06\")\n  |> filter(fn: (r) => r[\"_field\"] == \"Z_Overall\")\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\n  |> yield(name: \"last\")"
    }
   ]
  },
  {
   "title": "RPM",
   "type": "stat",
   "gridPos": { "h": 8, "w": 5, "x": 19, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"bucket\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"readings\")\n  |> filter(fn: (r) => r[\"deviceName\"] == \"Sensor06\")\n  |> filter(fn: (r) => r[\"_field\"] == \"RPM\")\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\n  |> yield(name: \"last\")"
    }
   ]
  },
  {
   "title": "Looseness Energy [(mm/s,rms)^2]",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"bucket\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"readings\")\n  |> filter(fn: (r) => r[\"deviceName\"] == \"Sensor06\")\n  |> filter(fn: (r) => r[\"_field\"] ==  \"Looseness\")\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\n  |> yield(name: \"last\")"
    }
   ]
  },
  {
   "title": "Unbalance Energy [(mm/s,rms)^2]",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 8, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"bucket\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"readings\")\n |> filter(fn: (r) => r[\"deviceName\"] == \"Sensor06\")\n  |> filter(fn: (r) => r[\"_field\"] == \"Unbalance\")\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\n  |> yield(name: \"last\")"
    }
   ]
  },
  {
   "title": "Misalignment  Energy [(mm/s,rms)^2]",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 16, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"bucket\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"readings\")\n  |> filter(fn: (r) => r[\"deviceName\"] == \"Sensor06\")\n  |> filter(fn: (r) => r[\"_field\"] == \"Misalignment\")\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\n  |> yield(name: \"last\")"
    }
   ]
  },
  { "type": "text", "gridPos": { "h": 2, "w": 24, "x": 0, "y": 12 }, "options": { "content": "Trend-Hourly" } },
  {
   "title": "Overall (mm/s,rms)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 14 },
   "targets": [
    {
     "query": "from(bucket: \"Hourly_Bucket\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"readings\")\n  |> filter(fn: (r) => r[\"deviceName\"] == \"Sensor06\")\n  |> filter(fn: (r) => r[\"_field\"] ==  \"X_Overall\" or r[\"resourceName\"] == \"Y_Overall\" or r[\"resourceName\"] == \"Z_Overall\")\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Failure mode [(mm/s,rms)^2]",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 22 },
   "targets": [
    {
     "query": "from(bucket: \"Hourly_Bucket\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"readings\")\n  |> filter(fn: (r) => r[\"deviceName\"] == \"Sensor06\")\n  |> filter(fn: (r) => r[\"_field\"] == \"Bearing\" or r[\"_field\"] == \"Unbalance\" or r[\"_field\"] == \"Misalignment\" or r[\"_field\"] == \"Looseness\" or r[\"_field\"] == \"Gear_mesh\" or r[\"_field\"] == \"Van_Pass\")\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> yield(name: \"mean\")"
    }
   ]
  },
  { "type": "text", "gridPos": { "h": 2, "w": 24, "x": 0, "y": 30 }, "options": { "content": "Trend-Daily" } },
  {
   "title": "X_Overall",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 0, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "d" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"Daily_Bucket\")\n  |> range(start: 2023-01-01T00:00:00Z)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"readings\")\n  |> filter(fn: (r) => r[\"deviceName\"] == \"Sensor06\")\n  |> filter(fn: (r) => r[\"_field\"] == \"X_Overall\")\n  |> difference(nonNegative: false, columns: [\"_value\"])\n  |> stateCount(fn: (r) => r._value >0, column: \"stateCount\") \n  |> map(fn: (r) => ({ r with _value: if r.stateCount >0 then r.stateCount else 0 })) \n  |> drop(columns: [\"stateCount\"]) \n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\n  |> yield(name: \"last\")"
    }
   ]
  },
  {
   "title": "Y_Overall",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 8, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "d" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"Daily_Bucket\")\n  |> range(start: 2023-01-01T00:00:00Z)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"readings\")\n  |> filter(fn: (r) => r[\"deviceName\"] == \"Sensor06\")\n  |> filter(fn: (r) => r[\"_field\"] == \"Y_Overall\")\n  |> difference(nonNegative: false, columns: [\"_value\"])\n  |> stateCount(fn: (r) => r._value >0, column: \"stateCount\") \n  |> map(fn: (r) => ({ r with _value: if r.stateCount >0 then r.stateCount else 0 })) \n  |> drop(columns: [\"stateCount\"]) \n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\n  |> yield(name: \"last\")"
    }
   ]
  },
  {
   "title": "Z_Overall",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 16, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "d" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"Daily_Bucket\")\n  |> range(start: 2023-01-01T00:00:00Z)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"readings\")\n  |> filter(fn: (r) => r[\"deviceName\"] == \"Sensor06\")\n  |> filter(fn: (r) => r[\"_field\"] == \"Z_Overall\")\n  |> difference(nonNegative: false, columns: [\"_value\"])\n  |> stateCount(fn: (r) => r._value >0, column: \"stateCount\") \n  |> map(fn: (r) => ({ r with _value: if r.stateCount >0 then r.stateCount else 0 })) \n  |> drop(columns: [\"stateCount\"]) \n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\n  |> yield(name: \"last\")"
    }
   ]
  },
  {
   "title": "Overall (mm/s,rms)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 36 },
   "targets": [
    {
     "query": "from(bucket: \"Daily_Bucket\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"readings\")\n  |> filter(fn: (r) => r[\"deviceName\"] == \"Sensor06\")\n  |> filter(fn: (r) => r[\"_field\"] ==  \"X_Overall\" or r[\"resourceName\"] == \"Y_Overall\" or r[\"resourceName\"] == \"Z_Overall\")\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Looseness Energy",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 0, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "d" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"Daily_Bucket\")\n  |> range(start: 2023-01-01T00:00:00Z)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"readings\")\n  |> filter(fn: (r) => r[\"deviceName\"] == \"Sensor06\")\n  |> filter(fn: (r) => r[\"_field\"] == \"Looseness\")\n  |> difference(nonNegative: false, columns: [\"_value\"])\n  |> stateCount(fn: (r) => r._value >0, column: \"stateCount\") \n  |> map(fn: (r) => ({ r with _value: if r.stateCount >0 then r.stateCount else 0 })) \n  |> drop(columns: [\"stateCount\"]) \n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\n  |> yield(name: \"last\")"
    }
   ]
  },
  {
   "title": "Unbalance Energy",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 8, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "d" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"Daily_Bucket\")\n  |> range(start: 2023-01-01T00:00:00Z)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"readings\")\n  |> filter(fn: (r) => r[\"deviceName\"] == \"Sensor06\")\n  |> filter(fn: (r) => r[\"_field\"] == \"Unbalance\")\n  |> difference(nonNegative: false, columns: [\"_value\"])\n  |> stateCount(fn: (r) => r._value >0, column: \"stateCount\") \n  |> map(fn: (r) => ({ r with _value: if r.stateCount >0 then r.stateCount else 0 })) \n  |> drop(columns: [\"stateCount\"]) \n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\n  |> yield(name: \"last\")"
    }
   ]
  },
  {
   "title": "Misalignment  Energy",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 16, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "d" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"Daily_Bucket\")\n  |> range(start: 2023-01-01T00:00:00Z)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"readings\")\n  |> filter(fn: (r) => r[\"deviceName\"] == \"Sensor06\")\n  |> filter(fn: (r) => r[\"_field\"] == \"Misalignment\")\n  |> difference(nonNegative: false, columns: [\"_value\"])\n  |> stateCount(fn: (r) => r._value >0, column: \"stateCount\") \n  |> map(fn: (r) => ({ r with _value: if r.stateCount >0 then r.stateCount else 0 })) \n  |> drop(columns: [\"stateCount\"]) \n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\n  |> yield(name: \"last\")"
    }
   ]
  },
  {
   "title": "Failure mode [(mm/s,rms)^2]",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 48 },
   "targets": [
    {
     "query": "from(bucket: \"Daily_Bucket\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"readings\")\n  |> filter(fn: (r) => r[\"deviceName\"] == \"Sensor06\")\n  |> filter(fn: (r) => r[\"_field\"] == \"Bearing\" or r[\"_field\"] == \"Unbalance\" or r[\"_field\"] == \"Misalignment\" or r[\"_field\"] == \"Looseness\" or r[\"_field\"] == \"Gear_mesh\" or r[\"_field\"] == \"Van_Pass\")\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> yield(name: \"mean\")"
    }
   ]
  }
 ]
}