{
 "title": "213MM2-R1-Template",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Panel Title",
   "type": "text",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 0 },
   "options": {
    "content": "<div class=\"bg\">\n    <img src=\"/public/img/texol/TEXOL Aurora 213MM2-R1.jpg\"\n    width=100% >\n  </div>\n"
   }
  },
  {
   "title": "X_Overall (mm/s,rms)",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 4, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"bucket\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"readings\")\n  |> filter(fn: (r) => r[\"deviceName\"] == \"Sensor01\")\n  \n  |> filter(fn: (r) => r[\"_field\"] == \"X_Overall\")\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\n  |> yield(name: \"last\")"
    }
   ]
  },
  {
   "title": "Y_Overall (mm/s,rms)",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 8, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"bucket\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"readings\")\n  |> filter(fn: (r) => r[\"deviceName\"] == \"Sensor01\")\n  \n  |> filter(fn: (r) => r[\"_field\"] == \"Y_Overall\")\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\n  |> yield(name: \"last\")"
    }
   ]
  },
  {
   "title": "Z_Overall (mm/s,rms)",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"bucket\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"readings\")\n  |> filter(fn: (r) => r[\"deviceName\"] == \"Sensor01\")\n  \n  |> filter(fn: (r) => r[\"_field\"] == \"Z_Overall\")\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\n  |> yield(name: \"last\")"
    }
   ]
  },
  {
   "title": "Temperature",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"bucket\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"readings\")\n  |> filter(fn: (r) => r[\"deviceName\"] == \"Sensor01\")\n  \n  |> filter(fn: (r) => r[\"_field\"] ==  \"Temperature_C\")\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\n  |> yield(name: \"last\")"
    }
   ]
  },
  {
   "title": "RPM",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 20, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"bucket\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"readings\")\n  |> filter(fn: (r) => r[\"deviceName\"] == \"Sensor01\")\n  \n  |> filter(fn: (r) => r[\"_field\"] == \"RPM\")\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\n  |> yield(name: \"last\")"
    }
   ]
  },
  {
   "title": "Bearing Defect",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"bucket\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"readings\")\n  |> filter(fn: (r) => r[\"deviceName\"] == \"Sensor01\")\n  \n  |> filter(fn: (r) => r[\"_field\"] ==  \"Bearing\")\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\n  |> yield(name: \"last\")"
    }
   ]
  },
  {
   "title": "Unbalance Energy [(mm/s,rms)^2]",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"bucket\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"readings\")\n |> filter(fn: (r) => r[\"deviceName\"] == \"Sensor01\")\n \n  |> filter(fn: (r) => r[\"_field\"] == \"Unbalance\")\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\n  |> yield(name: \"last\")"
    }
   ]
  },
  {
   "title": "Misalignment  Energy [(mm/s,rms)^2]",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"bucket\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"readings\")\n  |> filter(fn: (r) => r[\"deviceName\"] == \"Sensor01\")\n  \n  |> filter(fn: (r) => r[\"_field\"] == \"Misalignment\")\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\n  |> yield(name: \"last\")"
    }
   ]
  },
  {
   "title": "Losseness Energy [(mm/s,rms)^2]",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"bucket\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"readings\")\n  |> filter(fn: (r) => r[\"deviceName\"] == \"Sensor01\")\n  \n  |> filter(fn: (r) => r[\"_field\"] ==  \"Losseness\")\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\n  |> yield(name: \"last\")"
    }
   ]
  },
  {
   "title": "Gear_mesh Energy [(mm/s,rms)^2]",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"bucket\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"readings\")\n  |> filter(fn: (r) => r[\"deviceName\"] == \"Sensor01\")\n  \n  |> filter(fn: (r) => r[\"_field\"] == \"Gear_mesh\")\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\n  |> yield(name: \"last\")"
    }
   ]
  },
  {
   "title": "Van_Pass Energy [(mm/s,rms)^2]",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"bucket\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"readings\")\n  |> filter(fn: (r) => r[\"deviceName\"] == \"Sensor01\")\n  \n  |> filter(fn: (r) => r[\"_field\"] ==  \"Van_Pass\")\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\n  |> yield(name: \"last\")"
    }
   ]
  },
  {
   "title": "Bearing Energy Percentage",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"bucket\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"readings\")\n  |> filter(fn: (r) => r[\"deviceName\"] == \"Sensor01\")\n  \n  |> filter(fn: (r) => r[\"_field\"] ==  \"Bearing_percentage\")\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\n  |> yield(name: \"last\")"
    }
   ]
  },
  {
   "title": "Unbalance Energy Percentage",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"bucket\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"readings\")\n  |> filter(fn: (r) => r[\"deviceName\"] == \"Sensor01\")\n  \n  |> filter(fn: (r) => r[\"_field\"] ==  \"Unbalance_percentage\")\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\n  |> yield(name: \"last\")"
    }
   ]
  },
  {
   "title": "Misalignment Energy Percentage",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"bucket\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"readings\")\n  |> filter(fn: (r) => r[\"deviceName\"] == \"Sensor01\")\n  \n  |> filter(fn: (r) => r[\"_field\"] ==  \"Misalignment_percentage\")\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\n  |> yield(name: \"last\")"
    }
   ]
  },
  {
   "title": "Losseness Energy Percentage",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"bucket\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"readings\")\n  |> filter(fn: (r) => r[\"deviceName\"] == \"Sensor01\")\n  \n  |> filter(fn: (r) => r[\"_field\"] ==  \"Losseness_percentage\")\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\n  |> yield(name: \"last\")"
    }
   ]
  },
  {
   "title": "Gear_mesh Energy Percentage",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"bucket\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"readings\")\n  |> filter(fn: (r) => r[\"deviceName\"] == \"Sensor01\")\n  \n  |> filter(fn: (r) => r[\"_field\"] ==  \"Gear_mesh_percentage\")\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\n  |> yield(name: \"last\")"
    }
   ]
  },
  {
   "title": "Van_Pass Energy Percentage",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"bucket\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"readings\")\n  |> filter(fn: (r) => r[\"deviceName\"] == \"Sensor01\")\n  \n  |> filter(fn: (r) => r[\"_field\"] == \"Van_Pass_percentage\")\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\n  |> yield(name: \"last\")"
    }
   ]
  },
  { "type": "text", "gridPos": { "h": 2, "w": 24, "x": 0, "y": 16 }, "options": { "content": "Trend-Hourly" } },
  {
   "title": "Overall (mm/s,rms)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 18 },
   "targets": [
    {
     "query": "from(bucket: \"Hourly_Bucket\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"readings\")\n  |> filter(fn: (r) => r[\"deviceName\"] == \"Sensor01\")\n  \n  |> filter(fn: (r) => r[\"_field\"] ==  \"X_Overall\" or r[\"resourceName\"] == \"Y_Overall\" or r[\"resourceName\"] == \"Z_Overall\")\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Temperature",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "query": "from(bucket: \"Hourly_Bucket\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"readings\")\n  |> filter(fn: (r) => r[\"deviceName\"] == \"Sensor01\")\n  \n  |> filter(fn: (r) => r[\"_field\"] ==  \"Temperature_C\")\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Failure mode  [(mm/s,rms)^2]",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 34 },
   "targets": [
    {
     "query": "from(bucket: \"Hourly_Bucket\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"readings\")\n  |> filter(fn: (r) => r[\"deviceName\"] == \"Sensor01\")\n  \n  |> filter(fn: (r) => r[\"_field\"] == \"Bearing\" or r[\"_field\"] == \"Unbalance\" or r[\"_field\"] == \"Misalignment\" or r[\"_field\"] == \"Losseness\" or r[\"_field\"] == \"Gear_mesh\" or r[\"_field\"] == \"Van_Pass\")\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Failure mode_percentage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "query": "from(bucket: \"Hourly_Bucket\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"readings\")\n  |> filter(fn: (r) => r[\"deviceName\"] == \"Sensor01\")\n  \n  |> filter(fn: (r) => r[\"_field\"] == \"Bearing_percentage\" or r[\"_field\"] == \"Gear_mesh_percentage\" or r[\"_field\"] == \"Losseness_percentage\" or r[\"_field\"] == \"Misalignment_percentage\" or r[\"_field\"] == \"Unbalance_percentage\" or r[\"_field\"] == \"Van_Pass_percentage\")\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> yield(name: \"mean\")"
    }
   ]
  },
  { "type": "text", "gridPos": { "h": 2, "w": 24, "x": 0, "y": 50 }, "options": { "content": "Trend-Daily" } },
  {
   "title": "X_Overall",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 0, "y": 52 },
   "fieldConfig": { "defaults": { "unit": "d" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"Daily_Bucket\")\n  |> range(start: 2023-01-01T00:00:00Z)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"readings\")\n  |> filter(fn: (r) => r[\"deviceName\"] == \"Sensor01\")\n  \n  |> filter(fn: (r) => r[\"_field\"] == \"X_Overall\")\n  |> difference(nonNegative: false, columns: [\"_value\"])\n  |> stateCount(fn: (r) => r._value >0, column: \"stateCount\") \n  |> map(fn: (r) => ({ r with _value: if r.stateCount >0 then r.stateCount else 0 })) \n  |> drop(columns: [\"stateCount\"]) \n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\n  |> yield(name: \"last\")"
    }
   ]
  },
  {
   "title": "Y_Overall",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 8, "y": 52 },
   "fieldConfig": { "defaults": { "unit": "d" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"Daily_Bucket\")\n  |> range(start: 2023-01-01T00:00:00Z)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"readings\")\n  |> filter(fn: (r) => r[\"deviceName\"] == \"Sensor01\")\n  \n  |> filter(fn: (r) => r[\"_field\"] == \"Y_Overall\")\n  |> difference(nonNegative: false, columns: [\"_value\"])\n  |> stateCount(fn: (r) => r._value >0, column: \"stateCount\") \n  |> map(fn: (r) => ({ r with _value: if r.stateCount >0 then r.stateCount else 0 })) \n  |> drop(columns: [\"stateCount\"]) \n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\n  |> yield(name: \"last\")"
    }
   ]
  },
  {
   "title": "Z_Overall",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 16, "y": 52 },
   "fieldConfig": { "defaults": { "unit": "d" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"Daily_Bucket\")\n  |> range(start: 2023-01-01T00:00:00Z)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"readings\")\n  |> filter(fn: (r) => r[\"deviceName\"] == \"Sensor01\")\n  \n  |> filter(fn: (r) => r[\"_field\"] == \"Z_Overall\")\n  |> difference(nonNegative: false, columns: [\"_value\"])\n  |> stateCount(fn: (r) => r._value >0, column: \"stateCount\") \n  |> map(fn: (r) => ({ r with _value: if r.stateCount >0 then r.stateCount else 0 })) \n  |> drop(columns: [\"stateCount\"]) \n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\n  |> yield(name: \"last\")"
    }
   ]
  },
  {
   "title": "Overall (mm/s,rms)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 56 },
   "targets": [
    {
     "query": "from(bucket: \"Daily_Bucket\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"readings\")\n  |> filter(fn: (r) => r[\"deviceName\"] == \"Sensor01\")\n  \n  |> filter(fn: (r) => r[\"_field\"] ==  \"X_Overall\" or r[\"resourceName\"] == \"Y_Overall\" or r[\"resourceName\"] == \"Z_Overall\")\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Temperature",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 64 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "query": "from(bucket: \"Daily_Bucket\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"readings\")\n  |> filter(fn: (r) => r[\"deviceName\"] == \"Sensor01\")\n  \n  |> filter(fn: (r) => r[\"_field\"] ==  \"Temperature_C\")\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Bearing Energy",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 72 },
   "fieldConfig": { "defaults": { "unit": "d" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"Daily_Bucket\")\n  |> range(start: 2023-01-01T00:00:00Z)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"readings\")\n  |> filter(fn: (r) => r[\"deviceName\"] == \"Sensor01\")\n  \n  |> filter(fn: (r) => r[\"_field\"] == \"Bearing\")\n  |> difference(nonNegative: false, columns: [\"_value\"])\n  |> stateCount(fn: (r) => r._value >0, column: \"stateCount\") \n  |> map(fn: (r) => ({ r with _value: if r.stateCount >0 then r.stateCount else 0 })) \n  |> drop(columns: [\"stateCount\"]) \n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\n  |> yield(name: \"last\")"
    }
   ]
  },
  {
   "title": "Unbalance Energy",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 72 },
   "fieldConfig": { "defaults": { "unit": "d" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"Daily_Bucket\")\n  |> range(start: 2023-01-01T00:00:00Z)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"readings\")\n  |> filter(fn: (r) => r[\"deviceName\"] == \"Sensor01\")\n  \n  |> filter(fn: (r) => r[\"_field\"] == \"Unbalance\")\n  |> difference(nonNegative: false, columns: [\"_value\"])\n  |> stateCount(fn: (r) => r._value >0, column: \"stateCount\") \n  |> map(fn: (r) => ({ r with _value: if r.stateCount >0 then r.stateCount else 0 })) \n  |> drop(columns: [\"stateCount\"]) \n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\n  |> yield(name: \"last\")"
    }
   ]
  },
  {
   "title": "Misalignment Energy",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 72 },
   "fieldConfig": { "defaults": { "unit": "d" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"Daily_Bucket\")\n  |> range(start: 2023-01-01T00:00:00Z)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"readings\")\n  |> filter(fn: (r) => r[\"deviceName\"] == \"Sensor01\")\n  \n  |> filter(fn: (r) => r[\"_field\"] == \"Misalignment\")\n  |> difference(nonNegative: false, columns: [\"_value\"])\n  |> stateCount(fn: (r) => r._value >0, column: \"stateCount\") \n  |> map(fn: (r) => ({ r with _value: if r.stateCount >0 then r.stateCount else 0 })) \n  |> drop(columns: [\"stateCount\"]) \n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\n  |> yield(name: \"last\")"
    }
   ]
  },
  {
   "title": "Losseness Energy",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 72 },
   "fieldConfig": { "defaults": { "unit": "d" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"Daily_Bucket\")\n  |> range(start: 2023-01-01T00:00:00Z)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"readings\")\n  |> filter(fn: (r) => r[\"deviceName\"] == \"Sensor01\")\n  \n  |> filter(fn: (r) => r[\"_field\"] == \"Losseness\")\n  |> difference(nonNegative: false, columns: [\"_value\"])\n  |> stateCount(fn: (r) => r._value >0, column: \"stateCount\") \n  |> map(fn: (r) => ({ r with _value: if r.stateCount >0 then r.stateCount else 0 })) \n  |> drop(columns: [\"stateCount\"]) \n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\n  |> yield(name: \"last\")"
    }
   ]
  },
  {
   "title": "Gear_mesh Energy",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 72 },
   "fieldConfig": { "defaults": { "unit": "d" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"Daily_Bucket\")\n  |> range(start: 2023-01-01T00:00:00Z)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"readings\")\n  |> filter(fn: (r) => r[\"deviceName\"] == \"Sensor01\")\n  \n  |> filter(fn: (r) => r[\"_field\"] == \"Gear_mesh\")\n  |> difference(nonNegative: false, columns: [\"_value\"])\n  |> stateCount(fn: (r) => r._value >0, column: \"stateCount\") \n  |> map(fn: (r) => ({ r with _value: if r.stateCount >0 then r.stateCount else 0 })) \n  |> drop(columns: [\"stateCount\"]) \n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\n  |> yield(name: \"last\")"
    }
   ]
  },
  {
   "title": "Van_Pass Energy",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 72 },
   "fieldConfig": { "defaults": { "unit": "d" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"Daily_Bucket\")\n  |> range(start: 2023-01-01T00:00:00Z)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"readings\")\n  |> filter(fn: (r) => r[\"deviceName\"] == \"Sensor01\")\n  \n  |> filter(fn: (r) => r[\"_field\"] == \"Van_Pass\")\n  |> difference(nonNegative: false, columns: [\"_value\"])\n  |> stateCount(fn: (r) => r._value >0, column: \"stateCount\") \n  |> map(fn: (r) => ({ r with _value: if r.stateCount >0 then r.stateCount else 0 })) \n  |> drop(columns: [\"stateCount\"]) \n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\n  |> yield(name: \"last\")"
    }
   ]
  },
  {
   "title": "Failure mode  [(mm/s,rms)^2]",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 76 },
   "targets": [
    {
     "query": "from(bucket: \"Daily_Bucket\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"readings\")\n  |> filter(fn: (r) => r[\"deviceName\"] == \"Sensor01\")\n  \n  |> filter(fn: (r) => r[\"_field\"] == \"Bearing\" or r[\"_field\"] == \"Unbalance\" or r[\"_field\"] == \"Misalignment\" or r[\"_field\"] == \"Losseness\" or r[\"_field\"] == \"Gear_mesh\" or r[\"_field\"] == \"Van_Pass\")\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Failure mode_percentage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 84 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "query": "from(bucket: \"Daily_Bucket\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"readings\")\n  |> filter(fn: (r) => r[\"deviceName\"] == \"Sensor01\")\n  \n  |> filter(fn: (r) => r[\"_field\"] == \"Bearing_percentage\" or r[\"_field\"] == \"Gear_mesh_percentage\" or r[\"_field\"] == \"Losseness_percentage\" or r[\"_field\"] == \"Misalignment_percentage\" or r[\"_field\"] == \"Unbalance_percentage\" or r[\"_field\"] == \"Van_Pass_percentage\")\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> yield(name: \"mean\")"
    }
   ]
  }
 ]
}